# Generated by Django 3.0.8 on 2020-09-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200917_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
