# Generated by Django 3.0.8 on 2020-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.CharField(choices=[('In-Stock', 'In-Stock'), ('Out-Of-Stock', 'Out-Of-Stock')], default='In-Stock', max_length=12),
        ),
    ]
