# Generated by Django 3.0.8 on 2020-09-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200925_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='price',
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
