# Generated by Django 3.0.8 on 2020-09-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
