# Generated by Django 3.0.8 on 2020-09-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=255)),
                ('message', models.TextField()),
                ('contacted_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
